apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: logging
  labels:
    k8s-app: fluentd-cloudwatch
data:
  fluent.conf: |
    @include containers.conf
    @include systemd.conf
    <label @FLUENT_LOG>
      <match fluent.**>
        @type null
      </match>
    </label>
  elasticsearch.conf: |
    include_tag_key true
    host "#{ENV['FLUENT_ELASTICSEARCH_HOST']}"
    port "#{ENV['FLUENT_ELASTICSEARCH_PORT']}"
    path ""
    scheme "#{ENV['FLUENT_ELASTICSEARCH_SCHEME']}"
    ssl_verify true
    ssl_version TLSv1_2
    user
    password
    reload_connections false
    reconnect_on_error true
    reload_on_failure true
    log_es_400_reason false
    logstash_dateformat "%Y.%m.%d"
    logstash_format true    
    target_index_key
    type_name "fluentd"
    include_timestamp false
    template_name
    template_file
    template_overwrite false
    sniffer_class_name "Fluent::Plugin::ElasticsearchSimpleSniffer"
    request_timeout 5s
    application_name default
    suppress_type_name true
    enable_ilm false
    ilm_policy_id logstash-policy
    ilm_policy {}
    ilm_policy_overwrite false
    <buffer>
      flush_thread_count 8
      flush_interval 5s
      chunk_limit_size 2M
      queue_limit_length 32
      retry_max_interval 30
      retry_forever true
    </buffer>
  containers.conf: |
    <source>
      @type tail
      @id in_tail_container_logs
      @label @containers
      path /var/log/containers/*.log
      exclude_path ["/var/log/containers/fluentd*"]
      pos_file /var/log/fluentd-containers.log.pos
      tag container.*
      read_from_head true
      <parse>
        @type json
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </source>
    <label @containers>
      <filter container.**>
        @type kubernetes_metadata
        @id filter_container_kube_metadata
      </filter>
      <match container.**>
        @type rewrite_tag_filter
        <rule>
          key $.kubernetes.labels.type
          pattern /java/
          tag java.${tag}
        </rule>
        <rule>
          key $.kubernetes.container_name
          pattern .*
          tag common.${tag}
        </rule>
      </match>
      <filter **>
        @type record_transformer
        @id filter_containers_stream_transformer
        <record>
          stream_name ${tag_parts[5]}
        </record>
      </filter>
      <filter java.**>
        @type concat
        key log
        stream_identity_key $.kubernetes.pod_id
        multiline_start_regexp /^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}/
        continuous_line_regexp /^\D.*/
        separator ""
        timeout_label @concat_timeout
      </filter>
      <filter java.**>
        @type parser
        key_name log
        reserve_data true
        <parse>
          @type regexp
          expression /^(?<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3}*).*$/
          time_format %Y-%m-%d %H:%M:%S.%L                    
        </parse>
      </filter>
      <match **>
        @type elasticsearch
        @id out_es_containers
        @log_level "info"
        @include elasticsearch.conf
        logstash_prefix "logstash"
        index_name "logstash"
      </match>
    </label>
    <label @concat_timeout>
      <filter java.**>
        @type parser
        key_name log
        reserve_data true
        <parse>
          @type regexp
          expression /^(?<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3}*).*$/
          time_format %Y-%m-%d %H:%M:%S.%L                    
        </parse>
      </filter>
      <match **>
        @type elasticsearch
        @id out_es_java_error
        @log_level "info"
        @include elasticsearch.conf
        logstash_prefix "logstash-error"
        index_name "logstash-error"
      </match>
    </label>
    <label @ERROR>
      <match java.**>
        @type elasticsearch
        @id out_es_error
        @log_level "info"
        @include elasticsearch.conf
        logstash_prefix "logstash-error"
        index_name "logstash-error"
      </match>        
    </label>
  systemd.conf: |
    <source>
      @type systemd
      @id in_systemd_kubelet
      @label @systemd
      matches [{ "_SYSTEMD_UNIT": "kubelet.service" }]
      <entry>
        field_map {"MESSAGE": "message", "_HOSTNAME": "hostname", "_SYSTEMD_UNIT": "systemd_unit"}
        field_map_strict true
      </entry>
      path /var/log/journal
      <storage>
        @type local
        persistent true
        path /var/log/fluentd-journald-kubelet-pos.json
      </storage>
      read_from_head true
      tag kubelet.service
    </source>
    <source>
      @type systemd
      @id in_systemd_kubeproxy
      @label @systemd
      matches [{ "_SYSTEMD_UNIT": "kubeproxy.service" }]
      <entry>
        field_map {"MESSAGE": "message", "_HOSTNAME": "hostname", "_SYSTEMD_UNIT": "systemd_unit"}
        field_map_strict true
      </entry>
      path /var/log/journal
      <storage>
        @type local
        persistent true
        path /var/log/fluentd-journald-kubeproxy-pos.json
      </storage>
      read_from_head true
      tag kubeproxy.service
    </source>
    <source>
      @type systemd
      @id in_systemd_docker
      @label @systemd
      matches [{ "_SYSTEMD_UNIT": "docker.service" }]
      <entry>
        field_map {"MESSAGE": "message", "_HOSTNAME": "hostname", "_SYSTEMD_UNIT": "systemd_unit"}
        field_map_strict true
      </entry>
      path /var/log/journal
      <storage>
        @type local
        persistent true
        path /var/log/fluentd-journald-docker-pos.json
      </storage>
      read_from_head true
      tag docker.service
    </source>
    <label @systemd>
      <filter **>
        @type kubernetes_metadata
        @id filter_kube_metadata_systemd
      </filter>
      <filter **>
        @type record_transformer
        @id filter_systemd_stream_transformer
        <record>
          stream_name ${tag}-${record["hostname"]}
        </record>
      </filter>
      <match **>
        @type elasticsearch
        @id out_es_system
        @log_level "info"
        @include elasticsearch.conf
        logstash_prefix "logstash"
        index_name "logstash"
      </match>
    </label>